### PR TITLE
extra checks to prevent Tranquilizer of being stuck

### PR DESCRIPTION
**Pull request by isimonenko**

### CODE REVIEW

**Comment by logarithm** [comment]
Am I correct, that we found the reason beam stuck in our code and we don't need these sanity checks in tranquility?

**Comment by isimonenko** [comment]
@logarithm , Tranquilizer relies in its code on the Beam contract and at the same time has no control over what Beam implementation that is used, so it is still reasonable to have this checks.

**Comment by logarithm** [comment]
maybe also push it to druid upstream then?

**Comment by isimonenko** [comment]
Yep, I think it makes sense to push it upstream too

**Review by egor-ryashin — APPROVED** [review]
Looks ok.

**Review by logarithm — APPROVED** [review]

**Pull request merged**
